INSERT INTO PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.GIC_MEASURE_SUMMARY (
    GIC_ISSUANCE_DATE, LAST_UPDATED, GIC_ISSUANCE_CRITERIA, 
    LC_GIC_ISSUED_FLAG, MC_GIC_ISSUED_FLAG, 
    GIC_ISSUANCE_AMOUNT_LC, GIC_ISSUANCE_AMOUNT_MC, 
    GIC_ISSUANCE_AMOUNT_LC_FOR_KPI, GIC_ISSUANCE_AMOUNT_MC_FOR_KPI, 
    GIC_ISSUANCE_AMOUNT_TOTAL_FOR_KPI, RUN_DATE, RULE_RUN_TIME
)
WITH
-- Get the latest run time once to avoid multiple subqueries
RUN_INFO AS (
    SELECT 
        '2025-03-21' AS RUN_DATE,
        '08:00:00' AS RUN_TIME,
        (SELECT MAX(RUN_TIME) FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
         WHERE RUN_DATE = '2025-03-21') AS MAX_RUN_TIME
),
-- Get issuance criteria in a single operation
GIC_CRITERIA AS (
    SELECT 
        CASE
            WHEN EXISTS (SELECT 1 FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
                         WHERE RULE_ID = 2 AND RULE_STATUS = 'Meets Issuance Criteria' 
                         AND RUN_DATE = (SELECT RUN_DATE FROM RUN_INFO) 
                         AND RUN_TIME = (SELECT MAX_RUN_TIME FROM RUN_INFO))
            THEN 'A'
            WHEN EXISTS (SELECT 1 FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
                         WHERE RULE_ID = 3 AND RULE_STATUS = 'Meets Issuance Criteria' 
                         AND RUN_DATE = (SELECT RUN_DATE FROM RUN_INFO) 
                         AND RUN_TIME = (SELECT MAX_RUN_TIME FROM RUN_INFO))
            THEN 'B'
            ELSE 'NO CRITERIA'
        END AS GIC_ISSUANCE_CRITERIA
),
-- Set limits based on criteria
GIC_ISSUANCE_LIMIT AS (
    SELECT
        CASE WHEN (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) = 'A' THEN 500000000 ELSE 750000000 END AS GIC_ISSUANCE_LIMIT_QUARTER,
        CASE WHEN (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) = 'A' THEN 1500000000 ELSE 2000000000 END AS GIC_ISSUANCE_LIMIT_YEAR,
        5000000000 AS GIC_ISSUANCE_LIMIT_TOTAL
),
-- Get max dates in a single operation
MAX_DATES AS (
    SELECT
        MAX(POSITIONS_AS_OF_DATE) AS POSITIONS_MAX_DATE,
        MAX(INV_TRANSACTIONS_AS_OF_DATE) AS INV_TRANSACTIONS_MAX_DATE
    FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS 
    WHERE POSITIONS_AS_OF_DATE <= (SELECT RUN_DATE FROM RUN_INFO)
    AND INV_TRANSACTIONS_AS_OF_DATE <= (SELECT RUN_DATE FROM RUN_INFO)
),
-- Get max times for each date
MAX_TIME AS (
    SELECT
        (SELECT MAX(POSITIONS_INSERT_TIME) 
         FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS 
         WHERE POSITIONS_AS_OF_DATE = (SELECT POSITIONS_MAX_DATE FROM MAX_DATES)) AS POSITIONS_INSERT_TIME,
        (SELECT MAX(INV_TRANSACTIONS_INSERT_TIME) 
         FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS 
         WHERE INV_TRANSACTIONS_AS_OF_DATE = (SELECT INV_TRANSACTIONS_MAX_DATE FROM MAX_DATES)) AS INV_TRANSACTIONS_INSERT_TIME
),
-- Retrieve LC data in one operation and MC data in another to reduce redundant filters
LC_DATA AS (
    SELECT 
        COALESCE(p.GIC_ISSUANCE_QTD_VALUE, 0) AS GIC_ISSUED_LC_QUARTER,
        COALESCE(p.GIC_ISSUANCE_YTD_VALUE, 0) AS GIC_ISSUED_LC_YEAR,
        COALESCE(p.UNMATURED_GIC_VALUE, 0) AS GIC_ISSUED_LC_TOTAL,
        COALESCE(p.TOTAL_VAL_STRATEGIC_INDEX_FUND_VALUE, 0) AS AUM_LC
    FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS p
    WHERE p.FUND_TYPE = 'LargeCap'
    AND p.INV_TRANSACTIONS_AS_OF_DATE = (SELECT INV_TRANSACTIONS_MAX_DATE FROM MAX_DATES)
    AND p.INV_TRANSACTIONS_INSERT_TIME = (SELECT INV_TRANSACTIONS_INSERT_TIME FROM MAX_TIME)
    AND p.POSITIONS_AS_OF_DATE = (SELECT POSITIONS_MAX_DATE FROM MAX_DATES)
),
MC_DATA AS (
    SELECT 
        COALESCE(p.GIC_ISSUANCE_QTD_VALUE, 0) AS GIC_ISSUED_MC_QUARTER,
        COALESCE(p.GIC_ISSUANCE_YTD_VALUE, 0) AS GIC_ISSUED_MC_YEAR,
        COALESCE(p.UNMATURED_GIC_VALUE, 0) AS GIC_ISSUED_MC_TOTAL,
        COALESCE(p.TOTAL_VAL_STRATEGIC_INDEX_FUND_VALUE, 0) AS AUM_MC
    FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS p
    WHERE p.FUND_TYPE = 'MidCap'
    AND p.INV_TRANSACTIONS_AS_OF_DATE = (SELECT INV_TRANSACTIONS_MAX_DATE FROM MAX_DATES)
    AND p.INV_TRANSACTIONS_INSERT_TIME = (SELECT INV_TRANSACTIONS_INSERT_TIME FROM MAX_TIME)
    AND p.POSITIONS_AS_OF_DATE = (SELECT POSITIONS_MAX_DATE FROM MAX_DATES)
),
-- Consolidate the data from LC and MC
COMBINED_DATA AS (
    SELECT
        l.GIC_ISSUED_LC_QUARTER,
        l.GIC_ISSUED_LC_YEAR,
        l.GIC_ISSUED_LC_TOTAL,
        l.AUM_LC,
        m.GIC_ISSUED_MC_QUARTER,
        m.GIC_ISSUED_MC_YEAR,
        m.GIC_ISSUED_MC_TOTAL,
        m.AUM_MC
    FROM LC_DATA l, MC_DATA m
),
-- Calculate remaining limits
REMAINING_GIC_ISSUANCE_LIMIT AS (
    SELECT
        ROUND((l.GIC_ISSUANCE_LIMIT_QUARTER - (c.GIC_ISSUED_LC_QUARTER + c.GIC_ISSUED_MC_QUARTER)) / 1000000) * 1000000 AS GIC_REMAINING_LIMIT_QUARTER,
        ROUND((l.GIC_ISSUANCE_LIMIT_YEAR - (c.GIC_ISSUED_LC_YEAR + c.GIC_ISSUED_MC_YEAR)) / 1000000) * 1000000 AS GIC_REMAINING_LIMIT_YEAR,
        ROUND((l.GIC_ISSUANCE_LIMIT_TOTAL - (c.GIC_ISSUED_LC_TOTAL + c.GIC_ISSUED_MC_TOTAL)) / 1000000) * 1000000 AS GIC_REMAINING_LIMIT_TOTAL
    FROM GIC_ISSUANCE_LIMIT l, COMBINED_DATA c
),
-- Calculate target ratios
TARGET_GIC_ISSUANCE_RATIO AS (
    SELECT
        GREATEST(0.315 - ROUND((c.GIC_ISSUED_LC_TOTAL / NULLIF(c.AUM_LC, 0)), 4), 0) AS GIC_RATIO_LC,
        GREATEST(0.315 - ROUND((c.GIC_ISSUED_MC_TOTAL / NULLIF(c.AUM_MC, 0)), 4), 0) AS GIC_RATIO_MC
    FROM COMBINED_DATA c
),
-- Calculate target amounts
TARGET_GIC_ISSUANCE_AMOUNT AS (
    SELECT
        FLOOR(c.AUM_LC * r.GIC_RATIO_LC / 1000000) * 1000000 AS GIC_TARGET_LC,
        FLOOR(c.AUM_MC * r.GIC_RATIO_MC / 1000000) * 1000000 AS GIC_TARGET_MC,
        FLOOR(c.AUM_LC * r.GIC_RATIO_LC / 1000000) * 1000000 + 
        FLOOR(c.AUM_MC * r.GIC_RATIO_MC / 1000000) * 1000000 AS GIC_TARGET_TOTAL
    FROM COMBINED_DATA c, TARGET_GIC_ISSUANCE_RATIO r
),
-- Adjust based on limits
ADJUSTED_GIC_ISSUANCE_AMOUNT AS (
    SELECT
        LEAST(
            r.GIC_REMAINING_LIMIT_QUARTER,
            r.GIC_REMAINING_LIMIT_YEAR,
            r.GIC_REMAINING_LIMIT_TOTAL,
            t.GIC_TARGET_TOTAL
        ) AS GIC_TARGET_TOTAL_ADJUSTED,
        t.GIC_TARGET_LC,
        t.GIC_TARGET_MC,
        t.GIC_TARGET_TOTAL
    FROM REMAINING_GIC_ISSUANCE_LIMIT r, TARGET_GIC_ISSUANCE_AMOUNT t
),
-- Calculate pro-rata distribution
PRO_RATA_GIC_ISSUANCE AS (
    SELECT
        CASE 
            WHEN a.GIC_TARGET_TOTAL = 0 THEN 0
            ELSE ROUND(a.GIC_TARGET_TOTAL_ADJUSTED * (a.GIC_TARGET_LC / NULLIF(a.GIC_TARGET_TOTAL, 0)) / 1000000) * 1000000
        END AS GIC_TARGET_LC_PRO_RATA_ADJUSTED,
        CASE 
            WHEN a.GIC_TARGET_TOTAL = 0 THEN 0
            ELSE ROUND(a.GIC_TARGET_TOTAL_ADJUSTED * (a.GIC_TARGET_MC / NULLIF(a.GIC_TARGET_TOTAL, 0)) / 1000000) * 1000000
        END AS GIC_TARGET_MC_PRO_RATA_ADJUSTED
    FROM ADJUSTED_GIC_ISSUANCE_AMOUNT a
),
-- Cache rule failures for better performance
RULE_FAILURES AS (
    SELECT 
        RULE_ID
    FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
    WHERE RULE_STATUS = 'Does Not Meet Issuance Criteria' 
    AND RUN_DATE = (SELECT RUN_DATE FROM RUN_INFO)
),
-- Determine issuance flags
GIC_ISSUED_FLAG AS (
    SELECT
        CASE
            WHEN (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) = 'A' THEN
                CASE
                    WHEN EXISTS (SELECT 1 FROM RULE_FAILURES WHERE RULE_ID IN (4,5,6,7,8,9,10,12,13,14,15,24,26)) THEN FALSE
                    WHEN (SELECT GIC_TARGET_LC_PRO_RATA_ADJUSTED FROM PRO_RATA_GIC_ISSUANCE) < 10000000 THEN FALSE
                    ELSE TRUE
                END
            WHEN (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) = 'B' THEN
                CASE
                    WHEN EXISTS (SELECT 1 FROM RULE_FAILURES WHERE RULE_ID IN (4,5,6,7,8,9,17,19,20,21,22,24,26)) THEN FALSE
                    WHEN (SELECT GIC_TARGET_LC_PRO_RATA_ADJUSTED FROM PRO_RATA_GIC_ISSUANCE) < 10000000 THEN FALSE
                    ELSE TRUE
                END
            ELSE FALSE
        END AS LC_GIC_ISSUED_FLAG,
        CASE
            WHEN (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) = 'A' THEN
                CASE
                    WHEN EXISTS (SELECT 1 FROM RULE_FAILURES WHERE RULE_ID IN (4,5,6,7,8,9,11,12,13,14,16,25,26)) THEN FALSE
                    WHEN (SELECT GIC_TARGET_MC_PRO_RATA_ADJUSTED FROM PRO_RATA_GIC_ISSUANCE) < 10000000 THEN FALSE
                    ELSE TRUE
                END
            WHEN (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) = 'B' THEN
                CASE
                    WHEN EXISTS (SELECT 1 FROM RULE_FAILURES WHERE RULE_ID IN (4,5,6,7,8,18,19,20,21,23,25,26)) THEN FALSE
                    WHEN (SELECT GIC_TARGET_MC_PRO_RATA_ADJUSTED FROM PRO_RATA_GIC_ISSUANCE) < 10000000 THEN FALSE
                    ELSE TRUE
                END
            ELSE FALSE
        END AS MC_GIC_ISSUED_FLAG
),
-- Calculate KPI values
GIC_ISSUANCE_KPI AS (
    SELECT
        CASE
            WHEN p.GIC_TARGET_LC_PRO_RATA_ADJUSTED < 10000000 THEN 0
            WHEN f.LC_GIC_ISSUED_FLAG = FALSE THEN 0
            ELSE p.GIC_TARGET_LC_PRO_RATA_ADJUSTED
        END AS GIC_ISSUANCE_LC_FOR_KPI,
        CASE
            WHEN p.GIC_TARGET_MC_PRO_RATA_ADJUSTED < 10000000 THEN 0
            WHEN f.MC_GIC_ISSUED_FLAG = FALSE THEN 0
            ELSE p.GIC_TARGET_MC_PRO_RATA_ADJUSTED
        END AS GIC_ISSUANCE_MC_FOR_KPI,
        CASE
            WHEN p.GIC_TARGET_LC_PRO_RATA_ADJUSTED < 10000000 THEN 0
            WHEN f.LC_GIC_ISSUED_FLAG = FALSE THEN 0
            ELSE p.GIC_TARGET_LC_PRO_RATA_ADJUSTED
        END +
        CASE
            WHEN p.GIC_TARGET_MC_PRO_RATA_ADJUSTED < 10000000 THEN 0
            WHEN f.MC_GIC_ISSUED_FLAG = FALSE THEN 0
            ELSE p.GIC_TARGET_MC_PRO_RATA_ADJUSTED
        END AS GIC_ISSUANCE_TOTAL_FOR_KPI
    FROM PRO_RATA_GIC_ISSUANCE p, GIC_ISSUED_FLAG f
)
-- Final selection combining all calculations
SELECT
    (SELECT RUN_DATE FROM RUN_INFO) AS GIC_ISSUANCE_DATE,
    CURRENT_TIMESTAMP AS LAST_UPDATED,
    (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) AS GIC_ISSUANCE_CRITERIA,
    (SELECT LC_GIC_ISSUED_FLAG FROM GIC_ISSUED_FLAG) AS LC_GIC_ISSUED_FLAG,
    (SELECT MC_GIC_ISSUED_FLAG FROM GIC_ISSUED_FLAG) AS MC_GIC_ISSUED_FLAG,
    COALESCE((SELECT GIC_TARGET_LC_PRO_RATA_ADJUSTED FROM PRO_RATA_GIC_ISSUANCE), 0) AS GIC_ISSUANCE_AMOUNT_LC,
    COALESCE((SELECT GIC_TARGET_MC_PRO_RATA_ADJUSTED FROM PRO_RATA_GIC_ISSUANCE), 0) AS GIC_ISSUANCE_AMOUNT_MC,
    COALESCE((SELECT GIC_ISSUANCE_LC_FOR_KPI FROM GIC_ISSUANCE_KPI), 0) AS GIC_ISSUANCE_AMOUNT_LC_FOR_KPI,
    COALESCE((SELECT GIC_ISSUANCE_MC_FOR_KPI FROM GIC_ISSUANCE_KPI), 0) AS GIC_ISSUANCE_AMOUNT_MC_FOR_KPI,
    COALESCE((SELECT GIC_ISSUANCE_TOTAL_FOR_KPI FROM GIC_ISSUANCE_KPI), 0) AS GIC_ISSUANCE_AMOUNT_TOTAL_FOR_KPI,
    (SELECT RUN_DATE FROM RUN_INFO) AS RUN_DATE,
    (SELECT RUN_TIME FROM RUN_INFO) AS RULE_RUN_TIME;