CREATE OR REPLACE PROCEDURE PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.GIC_ISSUANCE_SUMMARY_PROCEDURE("RUN_DATE" DATE, "RUN_TIME" TIME(0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    -- Delete existing records for this run date
    DELETE FROM GIC_MEASURE_SUMMARY WHERE GIC_ISSUANCE_DATE = :RUN_DATE;
    
    -- Get latest run time for rule summary
    DECLARE LATEST_RULE_RUN_TIME TIME;
    SET LATEST_RULE_RUN_TIME = (SELECT MAX(RUN_TIME) FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY WHERE RUN_DATE = :RUN_DATE);
    
    -- Get max dates once
    DECLARE POSITIONS_MAX_DATE DATE;
    DECLARE INV_TRANSACTIONS_MAX_DATE DATE;
    SET POSITIONS_MAX_DATE = (SELECT MAX(POSITIONS_AS_OF_DATE) FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS WHERE POSITIONS_AS_OF_DATE <= :RUN_DATE);
    SET INV_TRANSACTIONS_MAX_DATE = (SELECT MAX(INV_TRANSACTIONS_AS_OF_DATE) FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS WHERE INV_TRANSACTIONS_AS_OF_DATE <= :RUN_DATE);
    
    -- Get max times once
    DECLARE POSITIONS_INSERT_TIME TIMESTAMP_NTZ;
    DECLARE INV_TRANSACTIONS_INSERT_TIME TIMESTAMP_NTZ;
    SET POSITIONS_INSERT_TIME = (SELECT MAX(POSITIONS_INSERT_TIME) FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS WHERE POSITIONS_AS_OF_DATE = :POSITIONS_MAX_DATE);
    SET INV_TRANSACTIONS_INSERT_TIME = (SELECT MAX(INV_TRANSACTIONS_INSERT_TIME) FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS WHERE INV_TRANSACTIONS_AS_OF_DATE = :INV_TRANSACTIONS_MAX_DATE);
    
    -- Perform the main insert with optimized CTEs
    INSERT INTO PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.GIC_MEASURE_SUMMARY (
        GIC_ISSUANCE_DATE, LAST_UPDATED, GIC_ISSUANCE_CRITERIA, 
        LC_GIC_ISSUED_FLAG, MC_GIC_ISSUED_FLAG, 
        GIC_ISSUANCE_AMOUNT_LC, GIC_ISSUANCE_AMOUNT_MC, 
        GIC_ISSUANCE_AMOUNT_LC_FOR_KPI, GIC_ISSUANCE_AMOUNT_MC_FOR_KPI, 
        GIC_ISSUANCE_AMOUNT_TOTAL_FOR_KPI, RUN_DATE, RULE_RUN_TIME
    )
    WITH
    -- Get GIC issuance criteria
    GIC_CRITERIA AS (
        SELECT 
            CASE
                WHEN RULE_ID = 2 AND RULE_STATUS = "Meets Issuance Criteria" THEN "A"
                WHEN RULE_ID = 3 AND RULE_STATUS = "Meets Issuance Criteria" THEN "B"
                ELSE "NO CRITERIA"
            END AS GIC_ISSUANCE_CRITERIA
        FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY
        WHERE RULE_ID IN (2, 3) 
        AND RULE_STATUS = "Meets Issuance Criteria"
        AND RUN_DATE = :RUN_DATE 
        AND RUN_TIME = :LATEST_RULE_RUN_TIME
    ),
    
    -- Get base positions and values data (reduce repeated queries)
    BASE_DATA AS (
        SELECT 
            FUND_TYPE,
            SUM(CASE WHEN FUND_TYPE = "LargeCap" AND INV_TRANSACTIONS_AS_OF_DATE = :INV_TRANSACTIONS_MAX_DATE 
                     AND INV_TRANSACTIONS_INSERT_TIME = :INV_TRANSACTIONS_INSERT_TIME
                 THEN GIC_ISSUANCE_QTD_VALUE ELSE 0 END) AS GIC_ISSUED_LC_QUARTER,
            SUM(CASE WHEN FUND_TYPE = "MidCap" AND INV_TRANSACTIONS_AS_OF_DATE = :INV_TRANSACTIONS_MAX_DATE 
                     AND INV_TRANSACTIONS_INSERT_TIME = :INV_TRANSACTIONS_INSERT_TIME
                 THEN GIC_ISSUANCE_QTD_VALUE ELSE 0 END) AS GIC_ISSUED_MC_QUARTER,
            SUM(CASE WHEN FUND_TYPE = "LargeCap" AND INV_TRANSACTIONS_AS_OF_DATE = :INV_TRANSACTIONS_MAX_DATE 
                     AND INV_TRANSACTIONS_INSERT_TIME = :INV_TRANSACTIONS_INSERT_TIME
                 THEN GIC_ISSUANCE_YTD_VALUE ELSE 0 END) AS GIC_ISSUED_LC_YEAR,
            SUM(CASE WHEN FUND_TYPE = "MidCap" AND INV_TRANSACTIONS_AS_OF_DATE = :INV_TRANSACTIONS_MAX_DATE 
                     AND INV_TRANSACTIONS_INSERT_TIME = :INV_TRANSACTIONS_INSERT_TIME 
                 THEN GIC_ISSUANCE_YTD_VALUE ELSE 0 END) AS GIC_ISSUED_MC_YEAR,
            SUM(CASE WHEN FUND_TYPE = "LargeCap" AND POSITIONS_AS_OF_DATE = :POSITIONS_MAX_DATE 
                     AND POSITIONS_INSERT_TIME = :POSITIONS_INSERT_TIME
                 THEN UNMATURED_GIC_VALUE ELSE 0 END) AS GIC_ISSUED_LC_TOTAL,
            SUM(CASE WHEN FUND_TYPE = "MidCap" AND POSITIONS_AS_OF_DATE = :POSITIONS_MAX_DATE 
                     AND POSITIONS_INSERT_TIME = :POSITIONS_INSERT_TIME
                 THEN UNMATURED_GIC_VALUE ELSE 0 END) AS GIC_ISSUED_MC_TOTAL,
            SUM(CASE WHEN FUND_TYPE = "LargeCap" AND POSITIONS_AS_OF_DATE = :POSITIONS_MAX_DATE
                 THEN TOTAL_VAL_STRATEGIC_INDEX_FUND_VALUE ELSE 0 END) AS AUM_LC,
            SUM(CASE WHEN FUND_TYPE = "MidCap" AND POSITIONS_AS_OF_DATE = :POSITIONS_MAX_DATE
                 THEN TOTAL_VAL_STRATEGIC_INDEX_FUND_VALUE ELSE 0 END) AS AUM_MC
        FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PRODUCER.GIC_POSITIONS_INV_TRANSACTIONS
        WHERE (POSITIONS_AS_OF_DATE = :POSITIONS_MAX_DATE OR INV_TRANSACTIONS_AS_OF_DATE = :INV_TRANSACTIONS_MAX_DATE)
        GROUP BY FUND_TYPE
    ),
    
    -- Aggregate totals
    AGGREGATED_DATA AS (
        SELECT
            SUM(GIC_ISSUED_LC_QUARTER) AS GIC_ISSUED_LC_QUARTER,
            SUM(GIC_ISSUED_MC_QUARTER) AS GIC_ISSUED_MC_QUARTER,
            SUM(GIC_ISSUED_LC_YEAR) AS GIC_ISSUED_LC_YEAR,
            SUM(GIC_ISSUED_MC_YEAR) AS GIC_ISSUED_MC_YEAR,
            SUM(GIC_ISSUED_LC_TOTAL) AS GIC_ISSUED_LC_TOTAL,
            SUM(GIC_ISSUED_MC_TOTAL) AS GIC_ISSUED_MC_TOTAL,
            SUM(AUM_LC) AS AUM_LC,
            SUM(AUM_MC) AS AUM_MC
        FROM BASE_DATA
    ),
    
    -- Get GIC issuance limits based on criteria
    GIC_ISSUANCE_LIMIT AS (
        SELECT
            CRITERIA.GIC_ISSUANCE_CRITERIA,
            CASE
                WHEN CRITERIA.GIC_ISSUANCE_CRITERIA = "A" THEN 500000000
                ELSE 750000000
            END AS GIC_ISSUANCE_LIMIT_QUARTER,
            CASE
                WHEN CRITERIA.GIC_ISSUANCE_CRITERIA = "A" THEN 1500000000
                ELSE 2000000000
            END AS GIC_ISSUANCE_LIMIT_YEAR,
            5000000000 AS GIC_ISSUANCE_LIMIT_TOTAL
        FROM (SELECT GIC_ISSUANCE_CRITERIA FROM GIC_CRITERIA) CRITERIA
    ),
    
    -- Calculate remaining GIC issuance limits
    REMAINING_GIC_ISSUANCE_LIMIT AS (
        SELECT
            GIL.GIC_ISSUANCE_CRITERIA,
            ROUND((GIL.GIC_ISSUANCE_LIMIT_QUARTER - (AGG.GIC_ISSUED_LC_QUARTER + AGG.GIC_ISSUED_MC_QUARTER)) / 1000000) * 1000000 AS GIC_REMAINING_LIMIT_QUARTER,
            ROUND((GIL.GIC_ISSUANCE_LIMIT_YEAR - (AGG.GIC_ISSUED_LC_YEAR + AGG.GIC_ISSUED_MC_YEAR)) / 1000000) * 1000000 AS GIC_REMAINING_LIMIT_YEAR,
            ROUND((GIL.GIC_ISSUANCE_LIMIT_TOTAL - (AGG.GIC_ISSUED_LC_TOTAL + AGG.GIC_ISSUED_MC_TOTAL)) / 1000000) * 1000000 AS GIC_REMAINING_LIMIT_TOTAL
        FROM GIC_ISSUANCE_LIMIT GIL, AGGREGATED_DATA AGG
    ),
    
    -- Calculate target GIC issuance ratios
    TARGET_GIC_ISSUANCE_RATIO AS (
        SELECT
            GREATEST(0.315 - ROUND((AGG.GIC_ISSUED_LC_TOTAL / NULLIF(AGG.AUM_LC, 0)), 4), 0) AS GIC_RATIO_LC,
            GREATEST(0.315 - ROUND((AGG.GIC_ISSUED_MC_TOTAL / NULLIF(AGG.AUM_MC, 0)), 4), 0) AS GIC_RATIO_MC
        FROM AGGREGATED_DATA AGG
    ),
    
    -- Calculate target GIC issuance amounts
    TARGET_GIC_ISSUANCE_AMOUNT AS (
        SELECT
            FLOOR(AGG.AUM_LC * RATIO.GIC_RATIO_LC / 1000000) * 1000000 AS GIC_TARGET_LC,
            FLOOR(AGG.AUM_MC * RATIO.GIC_RATIO_MC / 1000000) * 1000000 AS GIC_TARGET_MC,
            FLOOR(AGG.AUM_LC * RATIO.GIC_RATIO_LC / 1000000) * 1000000 + 
            FLOOR(AGG.AUM_MC * RATIO.GIC_RATIO_MC / 1000000) * 1000000 AS GIC_TARGET_TOTAL
        FROM AGGREGATED_DATA AGG, TARGET_GIC_ISSUANCE_RATIO RATIO
    ),
    
    -- Calculate adjusted GIC issuance amount
    ADJUSTED_GIC_ISSUANCE_AMOUNT AS (
        SELECT
            LEAST(
                RGIL.GIC_REMAINING_LIMIT_QUARTER,
                RGIL.GIC_REMAINING_LIMIT_YEAR,
                RGIL.GIC_REMAINING_LIMIT_TOTAL,
                TGIA.GIC_TARGET_TOTAL
            ) AS GIC_TARGET_TOTAL_ADJUSTED
        FROM REMAINING_GIC_ISSUANCE_LIMIT RGIL, TARGET_GIC_ISSUANCE_AMOUNT TGIA
    ),
    
    -- Calculate pro-rata distribution
    PRO_RATA_DISTRIBUTION AS (
        SELECT
            TGIA.GIC_TARGET_LC,
            TGIA.GIC_TARGET_MC,
            TGIA.GIC_TARGET_TOTAL,
            CASE 
                WHEN TGIA.GIC_TARGET_TOTAL = 0 THEN 0
                ELSE ROUND(TGIA.GIC_TARGET_LC / TGIA.GIC_TARGET_TOTAL, 2) 
            END AS GIC_TARGET_LC_PRO_RATA,
            CASE 
                WHEN TGIA.GIC_TARGET_TOTAL = 0 THEN 0
                ELSE ROUND(TGIA.GIC_TARGET_MC / TGIA.GIC_TARGET_TOTAL, 2) 
            END AS GIC_TARGET_MC_PRO_RATA
        FROM TARGET_GIC_ISSUANCE_AMOUNT TGIA
    ),
    
    -- Calculate pro-rata GIC issuance
    PRO_RATA_GIC_ISSUANCE AS (
        SELECT
            ROUND(AGIA.GIC_TARGET_TOTAL_ADJUSTED * PRD.GIC_TARGET_LC_PRO_RATA / 1000000) * 1000000 AS GIC_TARGET_LC_PRO_RATA_ADJUSTED,
            ROUND(AGIA.GIC_TARGET_TOTAL_ADJUSTED * PRD.GIC_TARGET_MC_PRO_RATA / 1000000) * 1000000 AS GIC_TARGET_MC_PRO_RATA_ADJUSTED
        FROM ADJUSTED_GIC_ISSUANCE_AMOUNT AGIA, PRO_RATA_DISTRIBUTION PRD
    ),
    
    -- Calculate GIC issuance flags
    GIC_ISSUED_FLAG AS (
        SELECT
            CASE
                WHEN GIC.GIC_ISSUANCE_CRITERIA = "A" THEN
                    CASE
                        WHEN EXISTS (
                            SELECT 1 FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
                            WHERE RULE_ID IN (4,5,6,7,8,9,10,12,13,14,15,24,26) 
                            AND RULE_STATUS = "Does Not Meet Issuance Criteria" 
                            AND RUN_DATE = :RUN_DATE
                        ) THEN FALSE
                        WHEN PRGI.GIC_TARGET_LC_PRO_RATA_ADJUSTED < 10000000 THEN FALSE
                        ELSE TRUE
                    END
                WHEN GIC.GIC_ISSUANCE_CRITERIA = "B" THEN
                    CASE
                        WHEN EXISTS (
                            SELECT 1 FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
                            WHERE RULE_ID IN (4,5,6,7,8,9,17,19,20,21,22,24,26) 
                            AND RULE_STATUS = "Does Not Meet Issuance Criteria" 
                            AND RUN_DATE = :RUN_DATE
                        ) THEN FALSE
                        WHEN PRGI.GIC_TARGET_LC_PRO_RATA_ADJUSTED < 10000000 THEN FALSE
                        ELSE TRUE
                    END
                ELSE FALSE
            END AS LC_GIC_ISSUED_FLAG,
            CASE
                WHEN GIC.GIC_ISSUANCE_CRITERIA = "A" THEN
                    CASE
                        WHEN EXISTS (
                            SELECT 1 FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
                            WHERE RULE_ID IN (4,5,6,7,8,9,11,12,13,14,16,25,26) 
                            AND RULE_STATUS = "Does Not Meet Issuance Criteria" 
                            AND RUN_DATE = :RUN_DATE
                        ) THEN FALSE
                        WHEN PRGI.GIC_TARGET_MC_PRO_RATA_ADJUSTED < 10000000 THEN FALSE
                        ELSE TRUE
                    END
                WHEN GIC.GIC_ISSUANCE_CRITERIA = "B" THEN
                    CASE
                        WHEN EXISTS (
                            SELECT 1 FROM PRINAM_PTDF_GIC_MONITORING_DATAMART_DEV.PUB.INDIVIDUAL_RULE_SUMMARY 
                            WHERE RULE_ID IN (4,5,6,7,8,18,19,20,21,23,25,26) 
                            AND RULE_STATUS = "Does Not Meet Issuance Criteria" 
                            AND RUN_DATE = :RUN_DATE
                        ) THEN FALSE
                        WHEN PRGI.GIC_TARGET_MC_PRO_RATA_ADJUSTED < 10000000 THEN FALSE
                        ELSE TRUE
                    END
                ELSE FALSE
            END AS MC_GIC_ISSUED_FLAG
        FROM GIC_CRITERIA GIC, PRO_RATA_GIC_ISSUANCE PRGI
    ),
    
    -- Calculate GIC issuance KPI
    GIC_ISSUANCE_KPI AS (
        SELECT
            CASE
                WHEN PRGI.GIC_TARGET_LC_PRO_RATA_ADJUSTED < 10000000 THEN 0
                WHEN GIF.LC_GIC_ISSUED_FLAG = FALSE THEN 0
                ELSE PRGI.GIC_TARGET_LC_PRO_RATA_ADJUSTED
            END AS GIC_ISSUANCE_LC_FOR_KPI,
            CASE
                WHEN PRGI.GIC_TARGET_MC_PRO_RATA_ADJUSTED < 10000000 THEN 0
                WHEN GIF.MC_GIC_ISSUED_FLAG = FALSE THEN 0
                ELSE PRGI.GIC_TARGET_MC_PRO_RATA_ADJUSTED
            END AS GIC_ISSUANCE_MC_FOR_KPI
        FROM PRO_RATA_GIC_ISSUANCE PRGI, GIC_ISSUED_FLAG GIF
    ),
    
    -- Calculate total KPI (fixing the missing calculation)
    TOTAL_KPI AS (
        SELECT
            GIK.GIC_ISSUANCE_LC_FOR_KPI,
            GIK.GIC_ISSUANCE_MC_FOR_KPI,
            GIK.GIC_ISSUANCE_LC_FOR_KPI + GIK.GIC_ISSUANCE_MC_FOR_KPI AS GIC_ISSUANCE_TOTAL_FOR_KPI
        FROM GIC_ISSUANCE_KPI GIK
    ),
    
    -- Create final view
    KPI_VIEW AS (
        SELECT
            :RUN_DATE AS GIC_ISSUANCE_DATE,
            CURRENT_TIMESTAMP AS LAST_UPDATED,
            GIC.GIC_ISSUANCE_CRITERIA,
            GIF.LC_GIC_ISSUED_FLAG,
            GIF.MC_GIC_ISSUED_FLAG,
            COALESCE(PRGI.GIC_TARGET_LC_PRO_RATA_ADJUSTED, 0) AS GIC_ISSUANCE_AMOUNT_LC,
            COALESCE(PRGI.GIC_TARGET_MC_PRO_RATA_ADJUSTED, 0) AS GIC_ISSUANCE_AMOUNT_MC,
            COALESCE(TK.GIC_ISSUANCE_LC_FOR_KPI, 0) AS GIC_ISSUANCE_AMOUNT_LC_FOR_KPI,
            COALESCE(TK.GIC_ISSUANCE_MC_FOR_KPI, 0) AS GIC_ISSUANCE_AMOUNT_MC_FOR_KPI,
            COALESCE(TK.GIC_ISSUANCE_TOTAL_FOR_KPI, 0) AS GIC_ISSUANCE_AMOUNT_TOTAL_FOR_KPI,
            :RUN_DATE AS RUN_DATE,
            :RUN_TIME AS RULE_RUN_TIME
        FROM 
            GIC_CRITERIA GIC,
            GIC_ISSUED_FLAG GIF,
            PRO_RATA_GIC_ISSUANCE PRGI,
            TOTAL_KPI TK
    )
    SELECT * FROM KPI_VIEW;
    
    RETURN ''GIC Issuance Summary Procedure Completed Successfully'';
END;
'